### ISSUE TITLE
error

### ISSUE THREAD

**Issue by apnansya** [attreyabhatt/Python-Music-Player#3]
i am getting error while importing ttk themes and making root= tk.themedTk() .what should i do to overcome this error.

i am getting this error:

Traceback (most recent call last):
  File "C:/Users/Ananya/PycharmProject/ananyaprakash/main.py", line 12, in <module>
    from ttkthemes import themed_tk as tk
  File "C:\Users\Ananya\Anaconda3\lib\site-packages\ttkthemes\__init__.py", line 6, in <module>
    from ttkthemes.themed_tk import ThemedTk
  File "C:\Users\Ananya\Anaconda3\lib\site-packages\ttkthemes\themed_tk.py", line 7, in <module>
    from ._widget import ThemedWidget
  File "C:\Users\Ananya\Anaconda3\lib\site-packages\ttkthemes\_widget.py", line 10, in <module>
    from PIL import Image, ImageEnhance
  File "C:\Users\Ananya\Anaconda3\lib\site-packages\PIL\Image.py", line 90, in <module>
    from . import _imaging as core
ImportError: DLL load failed: The specified module could not be found.

**Comment by ravikiran-pro** [comment]
@apnansya ttk themes are not packed  with tkinter ..it are just themes developed later.
so 
`pip install ttkthemes` 
will work
@attreyabhatt create requirements.txt ..It is just asking for lot of imports

**Comment by attreyabhatt** [comment]
Hey sorry. Probably forgot to mention that in the video.
Can you comment on the video so that I can pin it?

**Comment by bintangx1902** [comment]
im getting error while running the main.py

Traceback (most recent call last):
  File "C:\a-dev\music\main.py", line 73, in <module>
    root.iconbitmap(r'images/melody.ico')
  File "C:\Program Files\Python38\lib\tkinter\__init__.py", line 2071, in wm_iconbitmap
    return self.tk.call('wm', 'iconbitmap', self._w, bitmap)
_tkinter.TclError: bitmap "images/melody.ico" not defined

**Comment by ravikiran-pro** [comment]
hide that line on 73 comment and boom it works...u maybe or would have used operating system which don't allow using ico as app icon..
```
root.tk.call('wm', 'iconphoto', root._w, tk.PhotoImage(file=path'))
```
Try this

**Comment by Madhusudan9332** [comment]
> im getting error while running the main.py
> 
> Traceback (most recent call last): File "C:\a-dev\music\main.py", line 73, in root.iconbitmap(r'images/melody.ico') File "C:\Program Files\Python38\lib\tkinter__init__.py", line 2071, in wm_iconbitmap return self.tk.call('wm', 'iconbitmap', self._w, bitmap) _tkinter.TclError: bitmap "images/melody.ico" not defined

you have not defined images which is used in this code

**Comment by Kalpana-d1** [comment]
= RESTART: C:/Users/kalpa/AppData/Local/Programs/Python/Python311/music player python.py
pygame 2.3.0 (SDL 2.24.2, Python 3.11.3)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "C:/Users/kalpa/AppData/Local/Programs/Python/Python311/music player python.py", line 74, in <module>
    root.iconbitmap(r'images/melody.ico')
  File "C:\Users\kalpa\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 2136, in wm_iconbitmap
    return self.tk.call('wm', 'iconbitmap', self._w, bitmap)
_tkinter.TclError: bitmap "images/melody.ico" not defined


How can I solve this ??
